#!/bin/sh
# Regenerates shaders_spv.h from the GLSL sources. Run after editing a shader.
# Uses the glslc that ships with the NDK (ndk/<version>/shader-tools/<host>/glslc).
set -e

cd "$(dirname "$0")"

GLSLC="${GLSLC:-glslc}"
OUT=../shaders_spv.h

{
    echo "// Generated by shaders/compile_shaders.sh from video.vert, video.frag and video_planar.frag. Do not edit."
    echo "#pragma once"
    echo "#include <cstdint>"
    echo
    echo "static const uint32_t kVideoVertSpv[] ="
    "$GLSLC" -O --target-env=vulkan1.1 -mfmt=c -o - video.vert
    echo ";"
    echo
    echo "static const uint32_t kVideoFragSpv[] ="
    "$GLSLC" -O --target-env=vulkan1.1 -mfmt=c -o - video.frag
    echo ";"
    echo
    echo "static const uint32_t kVideoPlanarFragSpv[] ="
    "$GLSLC" -O --target-env=vulkan1.1 -mfmt=c -o - video_planar.frag
    echo ";"
} > "$OUT"

echo "Wrote $OUT"
